controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_contact:
    path: /contact
    controller: App\Controller\HomePageController::contact
    methods: ['GET','POST']